---
title: "sf_building_stock"
author: "Samantha Liu"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: false
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

library(sf)
library(leaflet)
library(tidyverse)
library(tidytransit)
library(mapboxapi)

mb_token <- "pk.eyJ1Ijoic2FtYW55bCIsImEiOiJjazlocGNvYWgxMHhxM2Rud2pxdzVnMnp2In0.D_j3K9tXiEddHH-8UUkeZQ"
```

```{r load-data, include = FALSE, eval = FALSE}
geom_land_use <- read_sf("https://data.sfgov.org/api/geospatial/us3s-fp9q?method=export&format=GeoJSON")
geom_zoning <- read_sf("https://data.sfgov.org/api/geospatial/3i4a-hu95?method=export&format=GeoJSON")
geom_planning <- read_sf("https://data.sfgov.org/api/geospatial/ttns-6zj3?method=export&format=GeoJSON")
geom_bldg_footprint <- read_sf("https://data.sfgov.org/api/geospatial/ynuv-fyni?method=export&format=GeoJSON")
gtfs_sfmta <- read_gtfs("https://gtfs.sfmta.com/transitdata/google_transit.zip")

saveRDS(geom_land_use, "sf_land_use.rds")
saveRDS(geom_zoning, "sf_zoning.rds")
saveRDS(geom_planning, "sf_planning.rds")
saveRDS(geom_bldg_footprint, "sf_bldg_footprint.rds")
saveRDS(gtfs_sfmta, "gtfs_sfmta.rds")
```

```{r transit-data, include = FALSE, eval = FALSE}
gtfs_sfmta <- readRDS("gtfs_sfmta.rds")

stops <- stops_as_sf(gtfs_sfmta$stops)
map_dfr(stops$geometry, function(x) {
  mb_isochrone(
    stops[x, ], 
    time = c(5), 
    profile = "walking", 
    id_column = "stop_id",
    access_token = mb_token
  )
}) %>% 
  left_join(
    stops %>% as.data.frame() %>% select(stop_id, stop_name), 
    by = c("id" = "stop_id")
  ) %>% 
  saveRDS("buffer_sfmta.rds")
```

```{r usps-data, include = FALSE, eval = FALSE}
library(ggmap)

# not a free service - API expires May 14, 2021
register_google(key = "AIzaSyButMqIpsOPTaMqccBCyAJ4rjWwvk9VUqs")

usps_sf <- 
  read_csv("G:/.shortcut-targets-by-id/1k9m-NVL2mrWxOYf52u2i3BHq8N141hNG/KIT SWITCH/10. REGULATION/C. Vacancy Analysis/san-francisco.csv") %>% 
  mutate(full_address = paste0(address, ", ", scity, ", CA ", szip))

for(i in 1:nrow(usps_sf)) {
  result <- geocode(usps_sf$full_address[i], output = "latlona", source = "google")
  usps_sf$lon[i] <- as.numeric(result[1])
  usps_sf$lat[i] <- as.numeric(result[2])
  # usps_sf$geoAddress[i] <- as.character(result[3])
}

usps_sf %>% 
  st_as_sf(coords = c(48, 49), crs = 4326) %>% # lon, lat
  saveRDS("usps_sf.rds")
```

## San Francisco Analysis
```{r load-geom}
sf_land_use <- readRDS("sf_land_use.rds") # last updated Sep 2019
sf_zoning <- readRDS("sf_zoning.rds") # last updated Feb 2021
sf_planning <- readRDS("sf_planning.rds") # last updated Sep 2019
sf_bldg_footprint <- readRDS("sf_bldg_footprint.rds") # last updated Dec 2020
buffer_sfmta <- readRDS("buffer_sfmta.rds")
gtfs_sfmta <- readRDS("gtfs_sfmta.rds")
usps_sf <- readRDS("usps_sf.rds") # last updated Jan 2021?

stops <- stops_as_sf(gtfs_sfmta$stops)

d <- sf_planning #%>% filter(pd_no == 9)
d_land_use <- 
  sf_land_use %>% 
  filter(landuse %in% c("VACANT", "RETAIL/ENT", "PDR", "MIPS", "VISITOR", "MIXED")) %>% 
  mutate(yrbuilt = as.numeric(yrbuilt)) %>% 
  filter(yrbuilt == 0 | (yrbuilt >= 1960 & yrbuilt < 2005)) %>% # including unknown data
  .[d, ]
d_zoning <- 
  sf_zoning %>% 
  filter(gen %in% c("Mixed Use", "Mixed")) %>% 
  .[d, ]
d_bldg_footprint <- 
  st_intersection(st_make_valid(sf_bldg_footprint), st_make_valid(d_zoning)) %>% 
  st_intersection(d_land_use) %>% 
  st_intersection(st_make_valid(sf_planning)) %>% 
  mutate(area_m2 = as.numeric(round(st_area(.)))) %>% 
  filter(area_m2 > 50) # corresponds to ~540 ft2

usps_sf <- 
  usps_sf %>% 
  filter(zoning %in% d_bldg_footprint$zoning_sim) %>% 
  filter(is.na(yearbuilt) | (yearbuilt >= 1960 & yearbuilt < 2005))
```

```{r color-palette}
cols <- 
  c(
    "#708d81", # olive green
    "#723d46", # maroon
    "#e26d5c", # salmon
    "#4281a4", # steel blue
    "#f5cb5c", # light yellow
    "#a78a7f" # taupe
  )

pal_land_use <- colorFactor(cols, domain = d_bldg_footprint$landuse)
pal_zoning <- colorFactor(cols, domain = d_bldg_footprint$zoning_sim)
pal_land_val <- colorNumeric("Spectral", domain = usps_sf %>% filter(!is.na(landval)) %>% pull(landval))
```

```{r plot-geom}
leaflet() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolygons(
    data = sf_planning,
    color = "black",
    fillOpacity = 0,
    weight = 1,
    dashArray = 3,
    label = ~pd_no,
    labelOptions = 
      labelOptions(
        noHide = T, 
        textOnly = TRUE, 
        style = list("font-weight" = "bold")
      ),
    group = "Planning Districts"
  ) %>%
  addPolygons(
    data = d_bldg_footprint,
    fillColor = ~pal_land_use(landuse),
    color = ~pal_land_use(landuse),
    fillOpacity = 0.5,
    weight = 1,
    label = ~districtna,
    group = "Land Use"
  ) %>%
  addPolygons(
    data = d_bldg_footprint,
    fillColor = ~pal_zoning(zoning_sim),
    color = ~pal_zoning(zoning_sim),
    fillOpacity = 0.5,
    weight = 1,
    label = ~districtna,
    group = "Zoning"
  ) %>%
  addPolygons(
    data = buffer_sfmta %>% st_union(),
    color = "#d3d3d3",
    fillOpacity = 0.6,
    weight = 1,
    group = "SFMTA Buffers"
  ) %>%
  addCircleMarkers(
    data = stops,
    color = "black",
    radius = 2,
    fillOpacity = 0.5,
    weight = 1,
    label = ~stop_name,
    group = "SFMTA Buffers"
  ) %>%
  addCircleMarkers(
    data = usps_sf,
    color = ~pal_land_val(landval),
    radius = 2,
    fillOpacity = 0.5,
    weight = 1,
    label = ~paste0("$", landval),
    group = "Vacant Lots"
  ) %>%
  addLegend(
    position = 'bottomleft',
    values = d_bldg_footprint$landuse,
    pal = pal_land_use,
    group = "Land Use"
  ) %>%
  addLegend(
    position = 'bottomleft',
    values = usps_sf %>% filter(!is.na(landval)) %>% pull(landval),
    pal = pal_land_val,
    group = "Vacant Lots"
  ) %>%
  addLegend(
    position = 'bottomleft',
    values = d_bldg_footprint$zoning_sim,
    pal = pal_zoning,
    group = "Zoning"
  ) %>%
  addLayersControl(
    overlayGroups = c("Planning Districts", "Land Use", "Zoning", "SFMTA Buffers", "Vacant Lots")
  ) %>% 
  hideGroup(c("Zoning", "SFMTA Buffers"))

```

```{r table}
results <- 
  d_bldg_footprint %>% 
  as.data.frame() %>% 
  select(objectid, p2010_zmaxn88ft, p2010_zminn88ft, landuse, med, retail, pdr, visitor, mips, cie, total_uses, resunits, area_m2) %>% 
  distinct(objectid, .keep_all = TRUE) %>% 
  mutate_if(names(.) != "landuse", as.numeric) %>% 
  group_by(landuse) %>% 
  summarize(
    count = n(),
    med = sum(med),
    retail = sum(retail),
    pdr = sum(pdr),
    visitor = sum(visitor),
    mips = sum(mips),
    cie = sum(cie),
    total_uses = sum(total_uses),
    resunits = sum(resunits),
    bldg_ft2 = round(sum(area_m2) * 10.764),
    avg_hgt_ft = mean(p2010_zmaxn88ft - p2010_zminn88ft, na.rm = TRUE)
  ) 
  # pivot_longer(
  #   cols = c(count, med, retail, pdr, visitor, mips, cie, total_uses, resunits, bldgsqft, shape_area, avg_hgt_ft),
  #   names_to = "land use"
  # ) %>% 
  # pivot_wider(names_from = landuse) %>% 
  # mutate_if(names(.) != "land use", round)

knitr::kable(results, format.args = list(big.mark = ","))
```
```{r district}
results <- 
  d_bldg_footprint %>% 
  as.data.frame() %>% 
  select(objectid, p2010_zmaxn88ft, p2010_zminn88ft, pd_no, med, retail, pdr, visitor, mips, cie, total_uses, resunits, area_m2) %>% 
  distinct(objectid, .keep_all = TRUE) %>% 
  mutate_all(as.numeric) %>% 
  group_by(pd_no) %>% 
  summarize(
    count = n(),
    med = sum(med),
    retail = sum(retail),
    pdr = sum(pdr),
    visitor = sum(visitor),
    mips = sum(mips),
    cie = sum(cie),
    total_uses = sum(total_uses),
    resunits = sum(resunits),
    bldg_ft2 = round(sum(area_m2) * 10.764),
    avg_hgt_ft = mean(p2010_zmaxn88ft - p2010_zminn88ft, na.rm = TRUE)
  ) 
  # pivot_longer(
  #   cols = c(count, med, retail, pdr, visitor, mips, cie, total_uses, resunits, bldgsqft, shape_area, avg_hgt_ft),
  #   names_to = "planning district"
  # ) %>% 
  # pivot_wider(names_from = pd_no) %>% 
  # mutate_if(names(.) != "planning district", round)

knitr::kable(results, format.args = list(big.mark = ","))
```

```{r zoning}
results <- 
  d_bldg_footprint %>% 
  as.data.frame() %>% 
  select(objectid, p2010_zmaxn88ft, p2010_zminn88ft, zoning_sim, med, retail, pdr, visitor, mips, cie, total_uses, resunits, area_m2) %>% 
  distinct(objectid, .keep_all = TRUE) %>% 
  mutate_if(names(.) != "zoning_sim", as.numeric) %>% 
  group_by(zoning_sim) %>% 
  summarize(
    count = n(),
    med = sum(med),
    retail = sum(retail),
    pdr = sum(pdr),
    visitor = sum(visitor),
    mips = sum(mips),
    cie = sum(cie),
    total_uses = sum(total_uses),
    resunits = sum(resunits),
    bldg_ft2 = round(sum(area_m2) * 10.764),
    avg_hgt_ft = mean(p2010_zmaxn88ft - p2010_zminn88ft, na.rm = TRUE)
  )  
  # pivot_longer(
  #   cols = c(count, med, retail, pdr, visitor, mips, cie, total_uses, resunits, bldgsqft, shape_area, avg_hgt_ft),
  #   names_to = "zoning class"
  # ) %>% 
  # pivot_wider(names_from = zoning_sim) %>% 
  # mutate_if(names(.) != "zoning class", round)

knitr::kable(results, format.args = list(big.mark = ","))
```
```{r additional-calcs}
# Total potential ft2
sum(results$bldg_ft2)

# % of buildings within 5 min of transit
(st_union(d_bldg_footprint) %>% st_difference(st_union(buffer_sfmta)) %>% st_area()) / 
  (st_union(d_bldg_footprint) %>% st_area()) * 100

# Count of matched usps and sf data
nrow(d_bldg_footprint[usps_sf, ])
```

